### ISSUE TITLE
Releases must be created only when new svg are added

### ISSUE THREAD

**Issue by oyelsv** [commitiouk/icons#12]
## Fix `release.yml` workflow

```yml
name: Publish to NPM

on:
  push:
    branches:
      - master     # triggered every time when any changes are pushed to master
...
``` 

### Suggested changes

```yml
name: Publish to NPM

on:
  push:
    branches:
      - master
    # Releases will be created only if some of the assets will be added/deleted
    paths: ["src/components/**", "static/**"]
...
```
